# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-19 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160721_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 3, 19, 13, 45, 15, 799576, tzinfo=utc)),
        ),
    ]
